### ISSUE TITLE
Trigger only error on deploy

### ISSUE THREAD

**Issue by fabnavigator** [mrgadget/node-red-contrib-eztimer#1]
Hi,

I'm a second day Node-RED user, so I might be doing something wrong, but I'm seeing this error in the debug window whenever I do a deploy. "Error stopping node: TypeError: Cannot read property 'timeout' of null" I get an error message for each eztimer node that is set for "trigger only".

Kind regards,

Bill

**Comment by mrgadget** [comment]
Hi Bill - I'm only about 2 months in myself - great product though isn't it?  Sorry to hear my timer isn't working so great for you though! 

I've used trigger nodes from the outset (one of the reasons I forked the timer) and haven't seen this - can you reproduce it reliably on new nodes you create?

I've not been able to reproduce it - though I do have a few changes queued up to push - I'll get that done probably this weekend and push an update then - this might bring with it a fix (or not!).

**Comment by fabnavigator** [comment]
Hi Ben,

I'm loving node-RED! I've setup all sorts of cool stuff that I never did with just HA.

I like your timer, and it seems to be working just fine. It's just those nasty debug entries whenever I deploy. I have three timers and I recreated them all from scratch. I have the same issue.

It's strange that the error occurs when trying to stop the node. I guess it ends up stopped anyway.

Here is an example that has this issue:

[
    {
        "id": "4bb71759.027528",
        "type": "eztimer",
        "z": "73e40fe8.2c675",
        "name": "test timer",
        "autoname": "17:00",
        "suspended": false,
        "lat": "38.87297",
        "lon": "-77.6616",
        "timerType": "2",
        "startupMessage": true,
        "ontype": "2",
        "ontimesun": "dawn",
        "ontimetod": "17:00",
        "onproperty": "payload",
        "onvaluetype": "num",
        "onvalue": 1,
        "onoffset": 0,
        "onrandomoffset": 0,
        "offtype": "1",
        "offtimesun": "dusk",
        "offtimetod": "dusk",
        "offduration": 0,
        "offproperty": "payload",
        "offvaluetype": "num",
        "offvalue": 0,
        "offoffset": 0,
        "offrandomoffset": 0,
        "mon": true,
        "tue": true,
        "wed": true,
        "thu": true,
        "fri": true,
        "sat": true,
        "sun": true,
        "x": 120,
        "y": 40,
        "wires": [
            []
        ]
    }
]

**Comment by mrgadget** [comment]
Hi Bill - I've finally pushed those changes, and I'm still unable to replicate this issue - can you update and give it another shot please?  Thanks!

**Comment by fabnavigator** [comment]
Hi Ben, I did the update and no longer see the error.  Thank you for fixing this.

**Comment by mrgadget** [comment]
Great! Thanks for reporting it!  Cheers.
