### ISSUE TITLE
pls do not give the Option "night" @ Sunevent

### ISSUE THREAD

**Issue by B0F1B0** [mrgadget/node-red-contrib-eztimer#11]
the geographical night is define as: 18° below the horizon.

source: "https://en.wikipedia.org/wiki/Twilight"

So, complete darkness does not occur for "some time" for many Regions on Earth who live above 48.7° of latitude. 

![error_above_48 7_degree](https://user-images.githubusercontent.com/39368417/59548893-7f2a9500-8f55-11e9-9566-57877a8f6663.png)

![Worldmap_above_48 7_degree](https://user-images.githubusercontent.com/39368417/59548950-31faf300-8f56-11e9-81fa-ba530822eb95.png)

source of picture:  "https://www.openstreetmap.org"

The Big problem is, that the "Node Red Flow" will work at "winter time" but will produce an error at "sommer time" for many people.

I would suggest not to give the option "night" @ Sunevent. 

There we have the salad,
B0F1B0

**Comment by mrgadget** [comment]
Interesting topic to read about!  I've given this some thought today - and I know `Night` is used by some people, so I'm not going to remove it as an option (would be a breaking-change).

I think I've worked out a better way.  `1.0.13` (available now) includes a fix whereby eztimer will automatically shift to the closest valid event.  For you, `night` doesn't exist during your summer, so `nauticalDusk` will be used instead.  A warning is emitted each time it runs and is re-scheduled letting you know that it wasn't able to be scheduled as intended - but the key is the node doesn't break.  In your winter, `night` will be valid, and will be used. 

![image](https://user-images.githubusercontent.com/700522/59550521-a453ed80-8fbf-11e9-8a09-5190641885fd.png)

Hope this works for you.

Cheers,
Ben.

**Comment by B0F1B0** [comment]
hi, 
really thank you for coding and that you response very quickly. 

i just updated to the newer version (1.0.13) and tried it out. But here comes an error message.

![Error_v1 0 13](https://user-images.githubusercontent.com/39368417/59550902-78aa1680-8f71-11e9-9836-9032eac2d90b.png)


There we have the salad,
B0F1B0

**Comment by mrgadget** [comment]
Aaand `1.0.14` drops.  I'd missed `nadir` out of the list of sun events that I was using to perform the regression.

Give that a shot - sorry about that.

**Comment by B0F1B0** [comment]
Hi, sorry dude, that i rise up your Version.

mega thanks for your very quick response. awesome. 
But i now work on the next "bug", maybey.

There we have the salad,
B0F1B0

**Comment by mrgadget** [comment]
Not stressed about version - easier to publish for people to test.  Thanks for reporting your issue - things like this I’d never know about as I live too close to the equator to be impacted.

Hopefully you won’t find any more, but if you do, you know how to find me!

Cheers,
Ben.

**Comment by B0F1B0** [comment]
the bug i tried to foce did not come.
Good job, mrgadget. 

There we have the salad,
B0F1B0
