### ISSUE TITLE
Trigger event output not as selected.

### ISSUE THREAD

**Issue by marc-gist** [mrgadget/node-red-contrib-eztimer#12]
I've setup eztimer (thank you for a great node) and recently tried to set it up as a trigger only, time of day (so set clock) and then set the output to send a "timestamp"

![image](https://user-images.githubusercontent.com/4084427/63689583-5980fe00-c7d8-11e9-8bab-8e29a5900558.png)

Payload is empty rather than a timestamp as expected.

**Comment by mrgadget** [comment]
Evening! So you found another value type I wasn't handling huh? :) Thanks!

Version 1.1.1 should sort this - just two lines of code to conditionally handle the `date` value type (displayed as `timestamp` in the UI).

Tested fine for me - let me know if you have any issues.

Cheers,
Ben.

**Comment by marc-gist** [comment]
Look like i did ;) as i've said, thank for the great node, using it more and more :)
