### ISSUE TITLE
timer control ontime not working

### ISSUE THREAD

**Issue by marc-gist** [mrgadget/node-red-contrib-eztimer#13]
used to work, not sure when it stopped.  Or perhaps just doesn't update the status?

`[{"id":"bf5fdc4.f54112","type":"eztimer","z":"d915f934.44fb08","name":"8:20 M-F Time to Leave","autoname":"8:20","tag":"","suspended":false,"sendEventsOnSuspend":false,"lat":"43.48446","lon":"-80.0662","timerType":"2","startupMessage":false,"ontype":"2","ontimesun":"dawn","ontimetod":"8:20","onproperty":"payload","onvaluetype":"num","onvalue":1,"onoffset":0,"onrandomoffset":0,"onsuppressrepeats":false,"offtype":"1","offtimesun":"dusk","offtimetod":"dusk","offduration":0,"offproperty":"payload","offvaluetype":"num","offvalue":0,"offoffset":0,"offrandomoffset":0,"offsuppressrepeats":false,"mon":true,"tue":true,"wed":true,"thu":true,"fri":true,"sat":false,"sun":false,"x":330,"y":1820,"wires":[[]]},{"id":"9638b139.cd757","type":"inject","z":"d915f934.44fb08","name":"","topic":"","payload":"{\"ontime\": \"10:45:00\"}","payloadType":"json","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":300,"y":1940,"wires":[["bf5fdc4.f54112"]]}]`

**Comment by marc-gist** [comment]
also sending in "on", "info" etc, get me

> TypeError: Cannot read property 'type' of null

in the debug console :(

**Comment by marc-gist** [comment]
more info: seems to happen only when set to "trigger only" as the timer type.

**Comment by mrgadget** [comment]
Gah.  Was related to my dynamic duration I introduced.  I had a typo in an if statement.

1.1.2 published, give it a shot. Sorry!

**Comment by marc-gist** [comment]
Thanks... the ontime now works; however, i still get the "TypeError:" message if i send in 'info' payload to get the current settings of the node.

**Comment by mrgadget** [comment]
try again :) a few breaking changes in the output payload sorry (changing the formatting of the JSON).

**Comment by marc-gist** [comment]
great, looks to be all good now!
