### ISSUE TITLE
Hide Lat/Long fields when not required

### ISSUE THREAD

**Issue by jhelmink** [mrgadget/node-red-contrib-eztimer#15]
Finally found a timer that could just trigger at a certain time of day!
In keeping with your ethos of a simple interface I suggest you hide the General Info - Lat/Long fields if they're not being used. I assume these are required only if a Sun Event has been selected?

**Comment by mrgadget** [comment]
Interesting idea! You're correct - they're only used if `Sun Event` is selected somewhere.

I see  the rationale behind this, but picture the UX of someone setting this up from scratch, running down the fields.  If it's hidden by default, it remains hidden until it's potentially off the screen and the user selects "Sun Event" for an `off` type.

Thoughts?

**Comment by jhelmink** [comment]
True, could set Sun Event as default so the fields are visible initially?

I think as someone uses it there should be an expectation of hidden UI elements if there are any hidden to begin with.
I would probably have a default state of "Select" for the Timer Type with no further sections shown.
Then once selected it would show the Trigger Event section or On/Off sections based on the selection.
Then same again for an Event Type which would show the relevant fields etc.
Downside is that it would be easier for people to save the node into a broken state where they haven't selected/completed the required fields, so would need error handling for that too.

So really - probably not worth the effort refactoring, people are smart enough to figure it out :)

**Comment by mrgadget** [comment]
I actually think the hiding lat/long idea has legs...  update your index.html file from my latest commit (b969c15) and see what you think.

**Comment by jhelmink** [comment]
Great - I tried it quickly this morning, a couple of bugs. 

1 - After the timer type is changed to Trigger, because the default for the off event type is Sun Calc, when the off event type is hidden the Lat/Long fields are still shown.
2 - Similar issue when opening an existing Timer, if it was saved with the Trigger set to manual, but off event type originally left as default to Sun Calc the Lat/Long fields are still shown.
3 - Very minor but noticed console complaining of duplicate id#node-input-tag at line 218/219

After looking at index.html I'm happy to submit some code if you like, but won't be until the weekend!

**Comment by mrgadget** [comment]
Thanks for the quick test/response.  Have (I think) squashed those three in a8aaf8d - let me know if there's anything else.  Always happy for contributions so feel free to submit a PR, no rush.

**Comment by jhelmink** [comment]
Nailed it! Tested it and all working well.
