### ISSUE TITLE
Trigger doesn't seem to work

### ISSUE THREAD

**Issue by bvmensvoort** [mrgadget/node-red-contrib-eztimer#17]
When using trigger type, nothing seems to get triggered.

This example flow has (optional) inject, a eztimer and a debug message.
But nothing happens at the set times (10:45:00 or 8:20:00) on a weekday.

```[{"id":"a5cb759b.aa0da8","type":"tab","label":"Flow` 1","disabled":false,"info":""},{"id":"822b5b05.7b4db8","type":"eztimer","z":"a5cb759b.aa0da8","name":"8:20 M-F Time to Leave","autoname":"8:20","tag":"","suspended":false,"sendEventsOnSuspend":false,"lat":"43.48446","lon":"-80.0662","timerType":"2","startupMessage":false,"ontype":"2","ontimesun":"dawn","ontimetod":"8:20","onproperty":"payload","onvaluetype":"num","onvalue":1,"onoffset":0,"onrandomoffset":0,"onsuppressrepeats":false,"offtype":"1","offtimesun":"dusk","offtimetod":"dusk","offduration":0,"offproperty":"payload","offvaluetype":"num","offvalue":0,"offoffset":0,"offrandomoffset":0,"offsuppressrepeats":false,"mon":true,"tue":true,"wed":true,"thu":true,"fri":true,"sat":false,"sun":false,"x":730,"y":500,"wires":[["9a70cff8.f769b"]]},{"id":"bd00b888.454678","type":"inject","z":"a5cb759b.aa0da8","name":"","topic":"","payload":"{\"ontime\": `\"10:45:00\"}","payloadType":"json","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":420,"y":500,"wires":[["822b5b05.7b4db8"]]},{"id":"9a70cff8.f769b","type":"debug","z":"a5cb759b.aa0da8","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":990,"y":500,"wires":[]}]```

**Comment by bvmensvoort** [comment]
Sorry, found it. The server time was different than local time.
The trigger flow works now.

**Comment by mrgadget** [comment]
I'm pleased it was an easy solution - really had me thinking as how this could be the first I'd know about such a major issue!  Thanks for continuing to troubleshoot and finding your issue rather than just raising a bug and leaving it for me, appreciate it 👍
