### ISSUE TITLE
on/off timer: wrong payload and value values when triggered by info

### ISSUE THREAD

**Issue by Export33** [mrgadget/node-red-contrib-eztimer#18]
Hi,

thanks for your effort on the timer.

When i trigger an on/off timer with an with `msg.payload = info` event i´m having some trouble with the result.

The values seem to be mixed up. Can you have a look at this?

| object               | value      | expected value  |
| -------------------- | ---------- | --------------- |
| payload.on.property  | msg.OnTest | msg.OnTest      |
| payload.on.value     | 0          | **Night**       |
| payload.off.property | msg.OnTest | **msg.payload** |
| payload.off.value    | 0          | **test**        |

![image](https://user-images.githubusercontent.com/25232960/67040970-e5ead580-f124-11e9-8fc8-b1648b1f07e0.png)

```[{"id":"38fe4c57.2a7b24","type":"debug","z":"f035508.fdbebb","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":410,"y":2040,"wires":[]},{"id":"80a6d3db.b07c4","type":"inject","z":"f035508.fdbebb","name":"info","topic":"payload","payload":"info","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":270,"y":1940,"wires":[["ff60548e.71cdb8"]]},{"id":"ff60548e.71cdb8","type":"eztimer","z":"f035508.fdbebb","name":"set Night","autoname":"night - dusk","tag":"eztimer","suspended":false,"sendEventsOnSuspend":false,"lat":"51.4995","lon":"7.4717","timerType":"1","startupMessage":false,"ontype":"1","ontimesun":"night","ontimetod":"17:00","onproperty":"OnTest","onvaluetype":"str","onvalue":"Night","onoffset":0,"onrandomoffset":0,"onsuppressrepeats":false,"offtype":"1","offtimesun":"dusk","offtimetod":"dusk","offduration":"00:01:00","offproperty":"payload","offvaluetype":"num","offvalue":"test","offoffset":0,"offrandomoffset":0,"offsuppressrepeats":false,"mon":true,"tue":true,"wed":true,"thu":true,"fri":true,"sat":true,"sun":true,"x":440,"y":1940,"wires":[["38fe4c57.2a7b24"]]}]```

**Comment by mrgadget** [comment]
Thanks for the detailed report and test flow - I'll have a look at this tonight (in ~12hrs) and report back.

**Comment by mrgadget** [comment]
Some fairly entry-level coding errors there!  Found and squashed though, I believe 1.1.5 (based on 9ea5e33) should behave as you'd expect it to.

Cheers,
Ben.

**Comment by Export33** [comment]
That works. Thank´s for the quick fix.

Cheers Export
