### ISSUE TITLE
ontime property does not seem to work

### ISSUE THREAD

**Issue by jdevine82** [mrgadget/node-red-contrib-eztimer#2]
Hi
I am only new so maybe reading the instructions wrong however the following basic flow does not seem to change the ontime...
`[
    {
        "id": "551f9a9a.3fe7ac",
        "type": "eztimer",
        "z": "78ad6fef.9c0bb",
        "name": "timer for air conditioner to turn off",
        "autoname": "00:00",
        "suspended": false,
        "lat": "-33.91642",
        "lon": "147.23387",
        "timerType": "2",
        "startupMessage": true,
        "ontype": "2",
        "ontimesun": "dawn",
        "ontimetod": "00:00",
        "onproperty": "payload",
        "onvaluetype": "num",
        "onvalue": "4",
        "onoffset": 0,
        "onrandomoffset": 0,
        "offtype": "1",
        "offtimesun": "dusk",
        "offtimetod": "dusk",
        "offduration": 0,
        "offproperty": "payload",
        "offvaluetype": "num",
        "offvalue": 0,
        "offoffset": 0,
        "offrandomoffset": 0,
        "mon": true,
        "tue": true,
        "wed": true,
        "thu": true,
        "fri": true,
        "sat": true,
        "sun": true,
        "x": 530,
        "y": 140,
        "wires": [
            []
        ]
    },
    {
        "id": "d5b21b2b.ec73c8",
        "type": "function",
        "z": "78ad6fef.9c0bb",
        "name": "get string values",
        "func": "\nvar newmsg = {payload: {ontime:\"05:45\"}}; \nreturn newmsg;",
        "outputs": 1,
        "noerr": 0,
        "x": 180,
        "y": 180,
        "wires": [
            [
                "551f9a9a.3fe7ac",
                "2f5d037e.a4282c"
            ]
        ]
    },
    {
        "id": "2f5d037e.a4282c",
        "type": "debug",
        "z": "78ad6fef.9c0bb",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "payload",
        "x": 480,
        "y": 260,
        "wires": []
    },
    {
        "id": "753b3a21.a4f92c",
        "type": "inject",
        "z": "78ad6fef.9c0bb",
        "name": "",
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "x": 120,
        "y": 80,
        "wires": [
            [
                "d5b21b2b.ec73c8"
            ]
        ]
    }
]`

**Comment by jdevine82** [comment]
I checked the upstream shedex node and it works in the same flow... However the trigger option is not on.

**Comment by mrgadget** [comment]
Great work pasting your flow - made checking it out easy.  Agree something's up, will have a look and come back to you.

**Comment by mrgadget** [comment]
Hi - I've just published a new version on npm (1.0.5) in which I repaired ontime/offtime, and added triggertime (as a nice-to-have alias to ontime).  Looks to work in my quick testing, give it a shot.

**Comment by jdevine82** [comment]
Hi
Yep works great. Thanks for adding trigger time. I really appreciate your work on this node. :)

**Comment by mrgadget** [comment]
Great stuff, no probs.  Saw a need for a simplified timer node with some decent functionality still so here we are.  Pleased it's of use to others also!  Cheers.
