### ISSUE TITLE
Info on Sun triggered event

### ISSUE THREAD

**Issue by Rzeszowiak** [mrgadget/node-red-contrib-eztimer#20]
Hi! Seems that "info" is not working while node is set for sun triggered event...
Getting: "TypeError: Cannot read property 'topic' of null" error

<code>
[{"id":"5e9cfc74.d5d804","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"efeec0fa.d158d","type":"debug","z":"5e9cfc74.d5d804","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","x":610,"y":160,"wires":[]},{"id":"543e3157.05871","type":"inject","z":"5e9cfc74.d5d804","name":"info","topic":"payload","payload":"info","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":210,"y":160,"wires":[["e25aa494.38d568"]]},{"id":"e25aa494.38d568","type":"eztimer","z":"5e9cfc74.d5d804","name":"triggered at Noon","autoname":"solarNoon","tag":"Noon","suspended":false,"sendEventsOnSuspend":false,"lat":"50.040609","lon":"21.999437","timerType":"2","startupMessage":false,"ontype":"1","ontimesun":"solarNoon","ontimetod":"17:00","onproperty":"OnTest","onvaluetype":"str","onvalue":"Noon","onoffset":0,"onrandomoffset":0,"onsuppressrepeats":false,"offtype":"1","offtimesun":"dusk","offtimetod":"dusk","offduration":"00:01:00","offproperty":"payload","offvaluetype":"num","offvalue":"test","offoffset":0,"offrandomoffset":0,"offsuppressrepeats":false,"mon":true,"tue":true,"wed":true,"thu":true,"fri":true,"sat":true,"sun":true,"x":410,"y":160,"wires":[["efeec0fa.d158d"]]}]
</code>

**Comment by mrgadget** [comment]
Hi Rzeszowiak - thanks for providing the flow.  I loaded and it runs without issue on the current version.  I did fix a few minor bugs in the `info` message recently (in the last 2-3 weeks) so can you please make sure you're running `1.1.5` of the node?  That should resolve your issues.

Thanks,
Ben.

**Comment by Rzeszowiak** [comment]
You are right. I had older version. After updating to 1.1.5 problem does not appear anymore. Thank you.
