### ISSUE TITLE
Type 'boolean' type is persisted as string "true" / "false"

### ISSUE THREAD

**Issue by LorenzKahl** [mrgadget/node-red-contrib-eztimer#24]
This happens at least when saving to a context like `global`.

![image](https://user-images.githubusercontent.com/301135/72468700-0e46a680-37de-11ea-97c4-0378da846093.png)

**Comment by mrgadget** [comment]
Cool - thanks for reporting. This should be a pretty fix - will give it a shot tonight and report back.

**Comment by mrgadget** [comment]
Interesting that the commit closed the issue!  Anyway - I believe this is sorted too - can you test when you have some time please?

Also picked up through fixing this, that emitting the value (ie, if you stored it in the `on` event, and emitted it in a message in the `off` event, it didn't work before, but it does now!

**Comment by mrgadget** [comment]
I'm going to go ahead and close this - feel free to re-open if you have issues.  This will be released to npm in a week or two as part of a rollup with a few other fixes/updates.
