### ISSUE TITLE
programmatic control doesn't work when "on" event is manual

### ISSUE THREAD

**Issue by moryoav** [mrgadget/node-red-contrib-eztimer#26]
weird bug here; programatically setting "offtime" or "duration" only works if on event is defined as something other than manual. If on event is "manual", then you can no longer programmatically control the off event. Here's a quick example of one flow that works and two that doesn't.

`[{"id":"46d08053.6030e","type":"tab","label":"Flow 2","disabled":false,"info":""},{"id":"3e05f308.1a2c8c","type":"eztimer","z":"46d08053.6030e","name":"works","autoname":"20:50 - ","tag":"eztimer","suspended":false,"sendEventsOnSuspend":false,"lat":"32.0853","lon":"34.7818","timerType":"1","startupMessage":false,"ontype":"2","ontimesun":"sunset","ontimetod":"20:50","onpropertytype":"msg","onproperty":"payload","onvaluetype":"str","onvalue":"on","onoffset":"0","onrandomoffset":0,"onsuppressrepeats":false,"offtype":"2","offtimesun":"dusk","offtimetod":"","offduration":"01:00:00","offpropertytype":"msg","offproperty":"payload","offvaluetype":"str","offvalue":"off","offoffset":0,"offrandomoffset":0,"offsuppressrepeats":false,"mon":true,"tue":true,"wed":true,"thu":true,"fri":true,"sat":false,"sun":true,"x":397.0057678222656,"y":107.01619720458984,"wires":[["d527b81c.5862e8"]]},{"id":"d527b81c.5862e8","type":"debug","z":"46d08053.6030e","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":700,"y":100,"wires":[]},{"id":"b29e7dd3.4cda4","type":"inject","z":"46d08053.6030e","name":"","topic":"","payload":"offtime 20:51","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":170,"y":100,"wires":[["3e05f308.1a2c8c"]]},{"id":"1082901f.d271e","type":"eztimer","z":"46d08053.6030e","name":"doesn't work","autoname":" - ","tag":"eztimer","suspended":false,"sendEventsOnSuspend":false,"lat":"32.0853","lon":"34.7818","timerType":"1","startupMessage":false,"ontype":"9","ontimesun":"sunset","ontimetod":"20:50","onpropertytype":"msg","onproperty":"payload","onvaluetype":"str","onvalue":"on","onoffset":"0","onrandomoffset":0,"onsuppressrepeats":false,"offtype":"2","offtimesun":"dusk","offtimetod":"","offduration":"01:00:00","offpropertytype":"msg","offproperty":"payload","offvaluetype":"str","offvalue":"off","offoffset":0,"offrandomoffset":0,"offsuppressrepeats":false,"mon":true,"tue":true,"wed":true,"thu":true,"fri":true,"sat":false,"sun":true,"x":370,"y":200,"wires":[["e94eeb42.7475f8"]]},{"id":"58e2bd0f.dd2164","type":"inject","z":"46d08053.6030e","name":"","topic":"","payload":"on","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":122.99423217773438,"y":192.98380279541016,"wires":[["1082901f.d271e"]]},{"id":"e94eeb42.7475f8","type":"debug","z":"46d08053.6030e","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":652.9942321777344,"y":192.98380279541016,"wires":[]},{"id":"41019be2.1a28e4","type":"inject","z":"46d08053.6030e","name":"","topic":"","payload":"offtime 20:53","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":142.99423217773438,"y":272.98380279541016,"wires":[["1082901f.d271e"]]},{"id":"f34ce8fe.33e3e8","type":"eztimer","z":"46d08053.6030e","name":"doesn't work","autoname":" + ","tag":"eztimer","suspended":false,"sendEventsOnSuspend":false,"lat":"32.0853","lon":"34.7818","timerType":"1","startupMessage":false,"ontype":"9","ontimesun":"sunset","ontimetod":"20:50","onpropertytype":"msg","onproperty":"payload","onvaluetype":"str","onvalue":"on","onoffset":"0","onrandomoffset":0,"onsuppressrepeats":false,"offtype":"3","offtimesun":"dusk","offtimetod":"","offduration":"","offpropertytype":"msg","offproperty":"payload","offvaluetype":"str","offvalue":"off","offoffset":0,"offrandomoffset":0,"offsuppressrepeats":false,"mon":true,"tue":true,"wed":true,"thu":true,"fri":true,"sat":false,"sun":true,"x":370,"y":340,"wires":[["ffeb7881.d04f28"]]},{"id":"4c4fd2ba.7f449c","type":"inject","z":"46d08053.6030e","name":"","topic":"","payload":"on","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":122.99423217773438,"y":332.98380279541016,"wires":[["f34ce8fe.33e3e8"]]},{"id":"ffeb7881.d04f28","type":"debug","z":"46d08053.6030e","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":652.9942321777344,"y":332.98380279541016,"wires":[]},{"id":"d7f8bec8.e0a17","type":"inject","z":"46d08053.6030e","name":"","topic":"","payload":"duration 00:02","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":142.99423217773438,"y":412.98380279541016,"wires":[["f34ce8fe.33e3e8"]]}]`

**Comment by mrgadget** [comment]
None of them work as you're expecting them to (for me) - with the top one, the issue is your input format.  The node expects (from what I recall) `msg.payload.offtime` or `msg.payload.ontime` - so when specifying an input to change a parameter, choose the _JSON_ option, and use a JSON object such as: `{"ontime": "21:50"}`.

What you're trying to do with the others is unsupported.  This is effectively changing the _event type_ of the timer dynamically.  A manual timer event is just that, manual.  It responds to `on` (or `trigger`) and `off` only.

If you want a timer that turns off at a specific time, pick `Time of Day` (or `Sun Event`).  You can leave the value blank if you like and set it programatically (using the object method above).

If you want a duration-based timer, set that as your `off` event type.  Again, you can leave this blank if you like, and set/update this using a payload object specifying a `duration` value.

Don't forget about the `info` input string - handy for finding out when the next events of each type are scheduled for.

If you have a use-case that doesn't work with the above, happy to discuss further.

**Comment by moryoav** [comment]
I'll simplify the example, to demonstrate my point.
2 flows. Both of them have on\off type eztimer nodes. Both flows have their off event set to "Time of Day" with blank time. In the second flow, the off time cannot be set programmatically. I have changed the input to JSON type  payload (it doesn't matter, string input also works, but that's not the point right now). Please notice how the "off event" is identical in the two flows. Time of Day and Empty string. I am not trying to change the type of the event, it stays "Time of Day" always (for the off event).

Simplified example:

`[{"id":"46d08053.6030e","type":"tab","label":"Flow 2","disabled":false,"info":""},{"id":"3e05f308.1a2c8c","type":"eztimer","z":"46d08053.6030e","name":"works","autoname":"9:51 - ","tag":"eztimer","suspended":false,"sendEventsOnSuspend":false,"lat":"32.0853","lon":"34.7818","timerType":"1","startupMessage":false,"ontype":"2","ontimesun":"sunset","ontimetod":"9:51","onpropertytype":"msg","onproperty":"payload","onvaluetype":"str","onvalue":"on","onoffset":"0","onrandomoffset":0,"onsuppressrepeats":false,"offtype":"2","offtimesun":"dusk","offtimetod":"","offduration":"01:00:00","offpropertytype":"msg","offproperty":"payload","offvaluetype":"str","offvalue":"off","offoffset":0,"offrandomoffset":0,"offsuppressrepeats":false,"mon":true,"tue":true,"wed":true,"thu":true,"fri":true,"sat":false,"sun":true,"x":390,"y":100,"wires":[["d527b81c.5862e8"]]},{"id":"d527b81c.5862e8","type":"debug","z":"46d08053.6030e","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":650,"y":100,"wires":[]},{"id":"b29e7dd3.4cda4","type":"inject","z":"46d08053.6030e","name":"","topic":"","payload":"{\"offtime\": \"09:52\"}","payloadType":"json","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":170,"y":100,"wires":[["3e05f308.1a2c8c"]]},{"id":"1082901f.d271e","type":"eztimer","z":"46d08053.6030e","name":"doesn't work","autoname":" - ","tag":"eztimer","suspended":false,"sendEventsOnSuspend":false,"lat":"32.0853","lon":"34.7818","timerType":"1","startupMessage":false,"ontype":"9","ontimesun":"sunset","ontimetod":"20:50","onpropertytype":"msg","onproperty":"payload","onvaluetype":"str","onvalue":"on","onoffset":"0","onrandomoffset":0,"onsuppressrepeats":false,"offtype":"2","offtimesun":"dusk","offtimetod":"","offduration":"01:00:00","offpropertytype":"msg","offproperty":"payload","offvaluetype":"str","offvalue":"off","offoffset":0,"offrandomoffset":0,"offsuppressrepeats":false,"mon":true,"tue":true,"wed":true,"thu":true,"fri":true,"sat":false,"sun":true,"x":410,"y":180,"wires":[["e94eeb42.7475f8"]]},{"id":"58e2bd0f.dd2164","type":"inject","z":"46d08053.6030e","name":"","topic":"","payload":"on","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":130,"y":180,"wires":[["1082901f.d271e"]]},{"id":"e94eeb42.7475f8","type":"debug","z":"46d08053.6030e","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":650,"y":180,"wires":[]},{"id":"41019be2.1a28e4","type":"inject","z":"46d08053.6030e","name":"","topic":"","payload":"{\"offtime\": \"09:52\"}","payloadType":"json","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":170,"y":220,"wires":[["1082901f.d271e"]]}]`

**Comment by mrgadget** [comment]
Understood - have a go now. A number of changes to cater for this.

**Comment by moryoav** [comment]
Works, thank you!

**Comment by mrgadget** [comment]
Excellent. Thanks for being patient and working through this with me. Will continue to run in a limited release for a while to make sure it all works as expected before deploying to npm.

Perhaps I should write some unit tests... ah well.  One day when I have some spare time!
