### ISSUE TITLE
[bug] status is wrong when redeploying

### ISSUE THREAD

**Issue by moryoav** [mrgadget/node-red-contrib-eztimer#27]
First, I apologize for bothering you so much with issues. I'm a very heavy eztimer user, it's very important for my home automation...
As for the current issue I discovered. To reproduce, set a timer node, I tried with on\off timer with Time of Day for both on and off. Wait for the On time to pass. The node with trigger On properly and the node status will change to On, Until [Of Time]. So far so good. Now redeploy Node-Red. 
The status changes to Off, Until [Next Day On Time]. So this is wrong. But when the actual original off time arrives, the node will properly trigger "Off". So the node status doesn't match the behavior. 
This is a minor issue, because the node works properly, it's just the status that's wrong upon re-deploy.

Thanks.

**Comment by mrgadget** [comment]
Hi - no problem with the issues, would rather fix anything that needs fixing anyway, before it catches others out.

For this issue - I don't have Node-Red in front of me at the moment. but it sounds to me you just need to check the `Send previous event on startup` checkbox.  I'm not sure how (or if) I can save state across deploys.

Also - make sure you're deploying only changed nodes (the red deploy button in Node-Red should only have one highlighted node) - this means that unless you've actually changed the eztimer node, it won't get redeployed - I'm sure you probably already know this, but thought I should put it here for other people who refer to this issue.

Cheers.

**Comment by moryoav** [comment]
Please notice that the node does work properly after a re-deploy. So if the On time has passed already and you redeploy then the Off event will indeed fire on the intended time, it's just the text in the status that's wrong. The text in the status doesn't reflect what's going to happen. If I output the debug log then it is also correct. So this is not about you needing to preserve the states across redeploys - that bit already works fine, it's just that the text in the status needs to match what's actually going to happen, and that's not the case today.
Setting `Send previous event on startup` is again not what I'm talking about because the events are in fact sent and fired properly, I'm only talking about the status text here.

**Comment by mrgadget** [comment]
Actually it is :) but it's just broken it would appear!  `Send previous event on startup` should do exactly what it says (including update the status).  If you have it set up Dawn to Dusk, for instance.  And then you re-deploy at lunch time.  The _last_ event was the `on` event at Dawn - so it should re-send the `on` event, and update the status.  It _does_ send the right event, but it doesn't update the status - so I'll fix that now.

**Comment by moryoav** [comment]
If the on event was properly fired at dawn then it may not always be good to retrigger the On at lunchtime after a redeploy. Something already happened at dawn, I don't always want this thing to happen again at lunchtime with another on trigger.

The Status text should reflect what's actually going to happen. If an event is going to be triggered at dusk now, then it makes no sense for the status text to read "off, until tomorrow at dawn", because that's just not true. It should say "on, until dusk".

**Comment by mrgadget** [comment]
Ok - yep, fair enough there.  Give that a shot.  I've updated the internal state only if not sending the event on startup, and run the `updateStatus()` routine afterwards.   Should be good I think!

**Comment by moryoav** [comment]
Everything is perfect now, thank you!

**Comment by mrgadget** [comment]
Good news! Cheers.
