### ISSUE TITLE
event value set to boolean sends string

### ISSUE THREAD

**Issue by marc-gist** [mrgadget/node-red-contrib-eztimer#3]
When setting a payload event, value to type "boolean", eztimer sends a string instead.
took me a long time to figure out why my automations weren't working with eztimer :(

**Comment by mrgadget** [comment]
Well spotted, sorry it cost you time! If you do an `npm update node-red-contrib-eztimer` (or update through the Node-Red web interface), it should be resolved - let me know! Cheers.

**Comment by marc-gist** [comment]
Awesome, thanks for the very quick fix! I'll test later today hopefully.

**Comment by mrgadget** [comment]
Hey, assuming the update sorted it for you?
