### ISSUE TITLE
Event times - request feature

### ISSUE THREAD

**Issue by Fires04** [mrgadget/node-red-contrib-eztimer#30]
Hi, I search everywhere but I can't find an answer. It is possible to somehow emit also a time of events for example msg.times? That same time what is under node if it running ( ON until xxxxx ). 
It would be nice to have the opportunity to save this time for example for the countdown to the next sunrise etc.. 

Thanks for your nice work

**Comment by mrgadget** [comment]
Hey - thanks.  Would `info` work for you?

If you send the node a message with `msg.payload` set to `info` (string), it will emit a message detailing it's current setup/state - eg;
```json
{
  "name": "eztimer",
  "state": "off",
  "on": {
    "property": "msg.payload",
    "value": "on_test",
    "nextEvent": "Wed Apr 22 2020 06:45:23 GMT+1200 (New Zealand Standard Time)"
  },
  "off": {
    "property": "msg.payload",
    "value": "off_test",
    "nextEvent": "Wed Apr 22 2020 18:34:17 GMT+1200 (New Zealand Standard Time)"
  }
}
```
That give you what you need?

**Comment by Fires04** [comment]
Almost yes.. But it will be good if you could parse this info with an event
output value without request.

út 21. 4. 2020 v 13:19 odesílatel Ben Nuttall <notifications@github.com>
napsal:

**Comment by mrgadget** [comment]
Right, so how about we just emit the contents of `info` with every output (outside the `payload`) eg;
```json
msg = {
    "info": { },
    "tag": "eztimer",
    "payload": { }
}
```
Or maybe just do this as an option?  I don't want to clutter the UI with too many options though...

Thoughts?

**Comment by mrgadget** [comment]
@Fires04 - can you replace the index.js with the one from my latest commit and tell me if it works for you?  I think it will...  Thanks!

**Comment by Fires04** [comment]
Hi, nice work it works like charm. Just some little tweaks but it work flawlessly. Maybe you can send times in the current time zone (not as ISO8601 2020-04-27T03:10:19.846Z) as info under the node. But it is just a little conversion that needs to be done in flow. So thank you very much.

**Comment by mrgadget** [comment]
No problem - I don't actually send as UTC, I just send as-is.

It seems to be how Node-Red decides to display it (in debug) - might be related to issue #29?

For me, if I do a `.getTime()` on the `on.nextEvent` output, it returns the right number of seconds for the _local_ date, and if I do a `.toString()`, it shows the string representation in _local_ format too - is this how it behaves for you?

**Comment by Fires04** [comment]
You right. I think the datetime object is right way. Good work man.

**Comment by mrgadget** [comment]
You've got a working version - I'm just going to close this and push a version to NPM at a later date (when I have some more critical fixes or features).
