### ISSUE TITLE
Trigger for renewed schedule check 

### ISSUE THREAD

**Issue by o0shojo0o** [mrgadget/node-red-contrib-eztimer#31]
Hi, 
unfortunately I did not find what I was looking for so I am asking here.
  
Do I have the possibility to trigger eztimer so that it checks its schedule again and generates output again?

**Comment by mrgadget** [comment]
Hi @o0shojo0o - I'm not 100% sure what you're asking sorry.  

The node doesn't check anything - it has a timer that's set to fire on the next event which is set either;
1. on the last event, or,
2. when a change is made via an input.  

You can send `info` to the node at any time to emit a message containing information about current state and next triggers.

Does this answer your question?

**Comment by o0shojo0o** [comment]
Yes thank you that is the solution!
