### ISSUE TITLE
Using debug msg in flow

### ISSUE THREAD

**Issue by Francois1976** [mrgadget/node-red-contrib-eztimer#32]
Hi, i'm very happy with your EZtimer...  I would like to know if it's possible to extract and use the message sent by the timer in debug panel ( msg.string[64] )

I want to extract the planned "off" time to do some automation before the time is over.

I tryed many thing to use it in my flow without succes...

Thanks!

**Comment by mrgadget** [comment]
Great, thanks for the feedback!

I'm not sure I completely understand - you want to be able to view it in the debug window?  Could you put a debug node on the output, and send a payload of 'info' to the node?

**Comment by Francois1976** [comment]
I want to use the info sent in the debug panel by the timer.  See the picture.

It’s not the same as the “status”, the msg:string [64] always indicate the next “off time” as the [66] always indicate the next “on time”.

So I need to use the OFF time in my other flow…

Can you explain how to extract that particular message?

Thanks again!

Francois St-Jacques

**Comment by Francois1976** [comment]
![InkedCapture_LI](https://user-images.githubusercontent.com/54863964/81611493-2653be80-93a9-11ea-8647-1ec82c9515ed.jpg)

**Comment by mrgadget** [comment]
If you send the eztimer node a payload [string] of `info` it will output an object which should have everything you need.

**Comment by Francois1976** [comment]
Great!  That’s what I need.

Thanks!

**Comment by mrgadget** [comment]
Good news, enjoy!

FYI - I edited your comments just to strip out the email rubbish and make it more concise for people who come here wondering the same thing later on.
