### ISSUE TITLE
Re-emit output at timed intervals

### ISSUE THREAD

**Issue by JasonSwindle** [mrgadget/node-red-contrib-eztimer#37]
Howdy,

I'm looking to move off of BigTimer, but I cannot seem to figure out how to have eztimer re-emit the output at a timed internal like BigTimer does. Is this built in or do I need to use something else to re-trigger eztimer?

**Comment by mrgadget** [comment]
Hey.  This isn't something I've got in there at this stage.  Interested to know your use case?  

Keen to try and keep the interface as clean/basic as possible, but also nice to support as many use-cases as possible too.

**Comment by JasonSwindle** [comment]
Howdy,

Thanks for the reply.  In these flows, I control lights that need to be **always** on:

- Security lights
- Fish tank lights
- Snail growing tank (puffer fish has to eat :) )

and with the re-emit function, if someone turns it off, it will turn back on (barring no on unplugs the light). Right now I need to keep using BigTimer or place in some type of loop function before eztimer. 

## What I would like to see
An `Re-emit output every <SECONDS>` function in eztimer.

**Comment by mrgadget** [comment]
Hey - would appreciate if you could give this a shot and report back before I push it out to the wider user-base.

It's not in NPM yet, so you'll need to grab index.js and index.html and replace them in the node on your system.

Thanks!

**Comment by JasonSwindle** [comment]
I will give it a test today. Thank you. :)

**Comment by JasonSwindle** [comment]
Howdy,

Currently testing now. So far it is working great (See image attached). Two early feedbacks:

- This text:
> Note: Setting this above zero will re-emit the last scheduled output at this interval.

Reads oddly. Maybe something like "Setting this to zero (0) this disable this setting"?

- Give helper text on the different options? Like:
"s (seconds), m (minutes), h (hours), d (days), y (years)"

<br>
<br>

<br>
<br>

<br>
<br>

Re-emit every 1m (debug window)
![image](https://user-images.githubusercontent.com/1776251/94996858-b1a63a00-056c-11eb-805a-bd17f851c9b5.png)

**Comment by mrgadget** [comment]
Totally agree. Late night is my excuse. Will re-word, and perhaps a pointer to the help pane for formatting. 

What about: Checkbox to enable, which shows/hides the interval textbox accordingly? Could perhaps get away without the helper text then? I'm keen to keep it as uncluttered as possible.

**Comment by JasonSwindle** [comment]
Checkbox would be perfect, as it enabled the extra feature, and only then do you need to show the helper text. 🙂
________________________________

**Comment by mrgadget** [comment]
Have a look at that, let me know your thoughts.

**Comment by JasonSwindle** [comment]
Feedback:

- You use `resend` and `re-send`, best to pick one. ;D

Beyond that, ShipIt 👍

**Comment by mrgadget** [comment]
A long time coming but.... 1.2.5 published to npm and pulled through to Node-RED packages.
