### ISSUE TITLE
Possibility to turn on/off/cancel missing in "programatic control"

### ISSUE THREAD

**Issue by petter-b** [mrgadget/node-red-contrib-eztimer#38]
I just started to use this node. Although I found it quite useful I also found some potential for improvement.

Have the need to suspend the scheduling and at the same time make sure that the device controlled by the timer is turned on. To do this I figured that you need to first send a message with payload = "on" and then send another message with payload.suspend = true. 

I suggest that you add "turn_on", "turn_off" and "cancel" as new options under "programatic control".

**Comment by mrgadget** [comment]
I see your use-case, no doubt.  What about an `action` property that accepts the same commands as you'd normally use - so you could use a single message with the following payload:
```js
"payload": {
    "action": "on",
    "suspended": true
}
````

**Comment by petter-b** [comment]
Sure, this would be neat solution.

**Comment by mrgadget** [comment]
Hey - would appreciate if you could give this a shot and report back before I push it out to the wider user-base.

It's not in NPM yet, so you'll need to grab index.js and index.html and replace them in the node on your system.

Thanks!

**Comment by mrgadget** [comment]
1.2.5 published to npm and pulled through to Node-RED packages.
