### ISSUE TITLE
Input a new onpayload value does not seem to work

### ISSUE THREAD

**Issue by 19osiris89** [mrgadget/node-red-contrib-eztimer#4]
When I send a string into the eztimer "onpayload 22.0" to change the ON Payload but nothing happened. Maybe I dont understand the readme.

onpayload my_payload  - Sets the payload for the on event (no spaces)
Is "my_payload" a variable or just a example for a value?

Thanks for help

**Comment by mrgadget** [comment]
Hi,

The `onpayload` input keyword sets the payload that is sent when the `on` event is triggered. It is expected behaviour that the node doesn’t output anything when you send this input. 

What you’ve basically done is told the node that next time the on event is fired, send a message with a payload of 22. 

What are you trying to achieve? 

Cheers
Ben.

**Comment by 19osiris89** [comment]
Thank you for your quick replay!
The output is after the inject still the same. 

1. onpayload = 20
2. Injected onpayload 22.0
3. Trigger the onevent
4. onpayload  = 20 


[{"id":"3253941b.4c032c","type":"eztimer","z":"6a213046.eeee6","name":"Timer","autoname":"20:00 - 22:15","suspended":false,"sendEventsOnSuspend":false,"lat":"","lon":"","timerType":"1","startupMessage":true,"ontype":"2","ontimesun":"dawn","ontimetod":"20:00","onproperty":"payload","onvaluetype":"num","onvalue":"20","onoffset":0,"onrandomoffset":0,"offtype":"2","offtimesun":"dusk","offtimetod":"22:15","offduration":0,"offproperty":"payload","offvaluetype":"num","offvalue":"4","offoffset":0,"offrandomoffset":0,"mon":true,"tue":true,"wed":true,"thu":true,"fri":true,"sat":true,"sun":true,"x":362,"y":2681,"wires":[["83fede73.05e6c"]]},{"id":"70dea7c5.dcc348","type":"inject","z":"6a213046.eeee6","name":"","topic":"","payload":"onpayload 22.0","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":169,"y":2654,"wires":[["3253941b.4c032c"]]},{"id":"83fede73.05e6c","type":"debug","z":"6a213046.eeee6","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":561,"y":2669,"wires":[]},{"id":"c8b5c5f2.f89b38","type":"inject","z":"6a213046.eeee6","name":"","topic":"","payload":"on","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":137,"y":2703,"wires":[["3253941b.4c032c"]]},{"id":"6d615006.0aeca","type":"inject","z":"6a213046.eeee6","name":"","topic":"","payload":"offpayload 10","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":181,"y":2611,"wires":[["3253941b.4c032c"]]},{"id":"83c31242.bdee9","type":"inject","z":"6a213046.eeee6","name":"","topic":"","payload":"off","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":138,"y":2741,"wires":[["3253941b.4c032c"]]}]

**Comment by 19osiris89** [comment]
It has to be a bug:
because when I inject the string "onpayload 30" to node-red-contrib-eztimer nothing happend
when I inject the same string "onpayload 30" to node-red-contrib-schedex the on payload value is change.

**Comment by mrgadget** [comment]
Got it.  It is a bug.

Was/is a two-fold issue.
1) When I extended the functionality of schedex I moved the payload from simply being a string, to having the ability to be an object, string, integer etc.  In doing this, I moved it to the `value` property, as it you can choose any msg property to set, not just the payload.  As such, I've updated the commands to `onvalue` and `offvalue` respectively (and update the `value` property of the node), and tested these to be working.  These are still dynamic values - ie, not reflected in the config of the node.
2) It's expecting an object not just a string. ie, you need to send it a payload of `{"onvalue": 20}`.

Give 1.0.7 a go, in NPM as of 5 mins ago.
