### ISSUE TITLE
Set on-off type

### ISSUE THREAD

**Issue by matt6575** [mrgadget/node-red-contrib-eztimer#40]
Is there a way to programmatically set the on or off type? I noticed that if I have it set to "Sun Event" If I then inject say "ontime 12:00:00" it doesn't work. I must set the type in the node to "Time Of Day" before being able to inject a time.

Thanks

**Comment by mrgadget** [comment]
You're dead right - setting the type is unsupported at the moment but having a quick think about it I can't see why that can't be changed. Will have a look at what's involved when I'm working on it this coming weekend.

**Comment by matt6575** [comment]
Thank you, appreciate your work.

Something I ran into that would be nice to have (although I made a work around in my flow already). I have a timer for a light the runs on a schedule but have a switch in the UI to toggle between timer mode and manual mode to allow me to force the light on/off. I know I can currently send an On or Off to the timer to manually over-ride the output but there doesn't seem to be a way to resume the schedule without just waiting for the next event to happen. I preferably would like to be able send a "resume" command to the timer that would cancel the manual over-ride and output the correct state based on the  current schedule and time.

Only other thing I've missed since switching to eztimer from big timer is the ability to send a msg to the timer to output the current state. Big timer does this, if you send a SYNC msg to the timer it just outputs the current state.

Again thanks for the work you put into eztimer.

**Comment by mrgadget** [comment]
Hey @matt6575, have a play with that if you can.  

First off, I've run with the `sync` command exactly as you described, seems logical.

Secondly - I've enabled programmable access to the `type` for each event.  See the README.md for details.  This is _not tested_ - it's late... let me know if you're not up for testing it, and I'll see what I can do.

I've also sat back and had a think and I believe most of the other functionality you're after is there in 1.2.5 (to be released shortly).  You can use a combination of the `action` payload property, along with the `suspended` property to do what you're after.   When you 'un-suspend' (ie, send a message with a payload of `{"suspended": false}`, the node's events are enumerated and the correct event is sent to get the node into the state it should be in at that time of day - I believe that's what you're asking for?

It's worth noting you can combine the `suspended` and `action` properties in the same message if you're wanting to, for example, suspend scheduling _and_ leave the timer in the `on` state, you could send a single message such as:
```js
{ "payload": 
  {
    "suspended": true,
    "action": "on"
  }
}
````
This is a flow I was testing with - thought I'd include a screenshot and export JSON (below) so you can have a play.  You need the latest code (1.2.5) from this repo for it all to work.
![image](https://user-images.githubusercontent.com/700522/98926554-53418380-253c-11eb-815a-b752fe6d0cda.png)
```js
[{"id":"af0ad10.36e673","type":"eztimer","z":"513ac85b.43f668","name":"testing","debug":true,"autoname":"22:00 - 23:00","tag":"","suspended":false,"sendEventsOnSuspend":false,"latLongSource":"manual","latLongHaZone":"zone.home","lat":"0","lon":"0","timerType":"1","startupMessage":true,"ontype":"2","ontimesun":"dawn","ontimetod":"22:00","onpropertytype":"msg","onproperty":"payload","onvaluetype":"num","onvalue":1,"onoffset":0,"onrandomoffset":0,"onsuppressrepeats":false,"offtype":"2","offtimesun":"dusk","offtimetod":"23:00","offduration":"00:00:10","offpropertytype":"msg","offproperty":"payload","offvaluetype":"num","offvalue":0,"offoffset":0,"offrandomoffset":0,"offsuppressrepeats":false,"resend":false,"resendInterval":"5s","mon":true,"tue":true,"wed":true,"thu":true,"fri":true,"sat":true,"sun":true,"x":470,"y":480,"wires":[["769392c0.4bb57c"]]},{"id":"769392c0.4bb57c","type":"debug","z":"513ac85b.43f668","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":655,"y":480,"wires":[]},{"id":"69005f9a.76231","type":"inject","z":"513ac85b.43f668","name":"","topic":"","payload":"{\"suspended\": true}","payloadType":"json","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":165,"y":405,"wires":[["af0ad10.36e673"]]},{"id":"4f00cc72.2b4434","type":"inject","z":"513ac85b.43f668","name":"","topic":"","payload":"sync","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":125,"y":585,"wires":[["af0ad10.36e673"]]},{"id":"f35a7f44.86928","type":"inject","z":"513ac85b.43f668","name":"","topic":"","payload":"{\"suspended\": false}","payloadType":"json","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":165,"y":450,"wires":[["af0ad10.36e673"]]},{"id":"38704caa.19ac04","type":"inject","z":"513ac85b.43f668","name":"","topic":"","payload":"{\"action\":\"on\"}","payloadType":"json","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":155,"y":495,"wires":[["af0ad10.36e673"]]},{"id":"e2f381b3.34a5f","type":"inject","z":"513ac85b.43f668","name":"","topic":"","payload":"{\"action\":\"off\"}","payloadType":"json","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":155,"y":540,"wires":[["af0ad10.36e673"]]},{"id":"39068d56.1f1542","type":"inject","z":"513ac85b.43f668","name":"","topic":"","payload":"{\"ontime\":\"07:30:00\"}","payloadType":"json","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":175,"y":360,"wires":[["af0ad10.36e673"]]}]
```
Let me know if I've mis-understood - it _is_ late!

**Comment by matt6575** [comment]
I believe you've understood perfectly what I was saying.

I've tested this out with a bunch of inject nodes and so far the timer seems to be reacting just as expected. The ontype/offtype also appears to be working correctly on first test.
I'll try implementing this in to my actual flow tomorrow and see how it goes but first impressions seems like it should go smoothly. I'll report back what I find, good or bad.

Thanks

**Comment by mrgadget** [comment]
Thanks  - it's worth noting that there's a potential error condition if, for example, you have the timer set to sun event, and you change to time-of-day, but don't set a time-of-day.  Will have a think about how to handle it - might be worth defaulting to 00:00:00 or something.

**Comment by matt6575** [comment]
I just tested that with a new timer, configured the node to SunEvent. then switched to time of day with an inject node and it seemed to half work. It seems that the timer defaulted to an ontime of 17:00 but offtime gave an "invalid time: dusk". This seems to line up with what I seen during configuring the node, that in the node if I switch to time of day for ontime it already has a time of 17:00 pre filled in, however switching offtime to time of day the time remains Dusk instead of defaulting to a valid time like the ontime does.

Defaulting to 00:00:00 would be fine I think. This condition would only exist though if you didn't configure a time of day in the node itself before hand correct? If I configure SunEvent and TimeOfDay ahead of time then switching back and forth programmatically isn't an issue because I've essentially preconfigured "default" values. If a person doesn't preconfigure those values in the node however defaulting to 00:00:00 and 01:00:00 for on/off time respectively seems reasonable. 

Another option might be that if those values aren't preconfigured by the user and aren't passed by a previous node the node just automatically goes into a suspend/manual/passthru  mode and only outputs whatever it receives on the input. I think this would be my preferred behavior.

**Comment by matt6575** [comment]
I've tested this in my flow and it's looking good. 

1. Sync works.
2. Switching between Time of Day and Sun Event programmatically works, 
3. When programmatically going from a suspended state to a not suspended state the timer outputs the correct state based on it's current timer type.

I haven't been able to generate any error conditions. This is assuming you preconfigure the node Time of Day times and lat/long for Sun Events. If you don't preconfigure times for the Time of Day then programmatically switch to Time of Day from SunEvent the on time defaults to 17:00 avoiding an error condition but the off time defaults to a value of Dusk which obviously isn't a valid time and causes an error condition. This personally doesn't bother me because it seems like those values should always be configured in the node anyways before hand by the programmer.

**Comment by mrgadget** [comment]
Awesome - thanks @matt6575, appreciate the time taken to test thoroughly.  Will put some code in to default to times as discussed (just to mitigate any possible errors) and then get it published to npm.

**Comment by necromn** [comment]
Heya @mrgadget  - this change is exactly what I need to complete my project. Are you pushing to NPM soon? -- edit:saw your comment in the other thread. I'll see if i can grab this repo and help testing.

**Comment by mrgadget** [comment]
Hey @necromn - good reminder, will have a look over the weekend.

**Comment by necromn** [comment]
Grabbed the report and it seems to be working well - I'll update if i encounter any issues.

**Comment by mrgadget** [comment]
Cool - thanks.  Worth noting I still haven't put any real error handling around those times - so long as inputs are valid, should be fine.  Would like to wrap some handling around it going forward, but just don't have the time spare at the moment!

**Comment by mrgadget** [comment]
1.2.5 published to npm and pulled through to Node-RED packages.
