### ISSUE TITLE
msg.payload cancel does not cancel the current run, but sets a new end time

### ISSUE THREAD

**Issue by wokkeltje13** [mrgadget/node-red-contrib-eztimer#42]
I use the eztimer to start and stop a light at a random time when we are not at home. I want to sent a "cancel" when we arrive home when the timer is running so the light is not going out when we are at home. the cancel should stop the timer without sending an off event. But it is not stopping the timer, it just sets a new random stop time. I use latest version of ezhome and node-red. can this be an issue or am I doing wrong?

`[{"id":"592e1d79.022884","type":"eztimer","z":"84aa0aec.49b6d8","name":"Dusk - 22:00","debug":true,"autoname":" - 22:00:00","tag":"eztimer","suspended":false,"sendEventsOnSuspend":false,"latLongSource":"manual","latLongHaZone":"zone.home","lat":"","lon":"","timerType":"1","startupMessage":false,"ontype":"9","ontimesun":"dawn","ontimetod":"17:00","onpropertytype":"msg","onproperty":"payload","onvaluetype":"str","onvalue":"on","onoffset":0,"onrandomoffset":0,"onsuppressrepeats":false,"offtype":"2","offtimesun":"dusk","offtimetod":"22:00:00","offduration":"00:01:00","offpropertytype":"msg","offproperty":"payload","offvaluetype":"str","offvalue":"off","offoffset":"30","offrandomoffset":true,"offsuppressrepeats":false,"resend":false,"resendInterval":"0s","mon":true,"tue":true,"wed":true,"thu":true,"fri":true,"sat":true,"sun":true,"x":630,"y":100,"wires":[["5de15b3f.21a844"]]}]`

**Comment by mrgadget** [comment]
Nothing you're doing wrong - agree that is odd behaviour, thanks for picking it up.  I've updated the cancel routine to set the current state to `off`, prior to re-scheduling so it will correctly schedule the next event as the next `on` time instead.

Have implemented the fix as 1.2.6 and pushed to Node RED, you should be able to do an update now.

Let me know how it goes.

**Comment by wokkeltje13** [comment]
thanks for the quick response, after the update it works like expected.

**Comment by mrgadget** [comment]
No probs - thanks for the prompt feedback.  Glad it now works as it should.
