### ISSUE TITLE
Ad UI support for topic

### ISSUE THREAD

**Issue by ChristianMayer** [mrgadget/node-red-contrib-eztimer#43]
By setting the node config though the GUI I could set a value for `tag` (something that no other node I'm using is taking note of) but not for `topic` (something that is relevant for many nodes).

Feature request:
Please support setting the value for `topic` that is then added to the sent message from the eztimer node.

**Comment by mrgadget** [comment]
Fair enough, would this need to be attached to each event (like `value`), or one value for the node (like `tag`)?

**Comment by ChristianMayer** [comment]
For me it would be fine to be the same in every `msg`, i.e. just like `tag`.

I'm sure you'll find people who want it per event as it's more universal - but I'd prefer to keep things simple and reduce complexity. This will help in the long run.

**Comment by mrgadget** [comment]
Added topic in 654e6c6 - will publish as 1.2.7 shortly.

**Comment by mrgadget** [comment]
Published 1.2.7.  Should be good to update in a day or so.

**Comment by ChristianMayer** [comment]
Thank you!
