### ISSUE TITLE
when schedule is off an no manual on event is triggered, still trigger next day

### ISSUE THREAD

**Issue by wokkeltje13** [mrgadget/node-red-contrib-eztimer#44]
still an issue/remark after yesterday fix? 
after sending cancel, the action is stopped without sending off, so far so good. But I set the on trigger to manual, so I should not expect to receive a new schedule tomorrow except if I sent a new 'on' payload. currently I receive a new off event when the schedule is off.

**Comment by mrgadget** [comment]
When you put it `manual`, does the node say `suspended` in it's info text?

**Comment by wokkeltje13** [comment]
manual is not accepted as msg.payload (unsupported input)

**Comment by mrgadget** [comment]
It's not a text command - as per the docs it's a boolean (true/false) parameter (as you need to be able to turn it on/off) that's just an alias of `suspended`.

To set to manual (aka suspend), you'd need to send a payload of:
```js
{ "manual": true }
```

You could do this at the same time as you cancel the timer by sending:
```js
{
    "action": "cancel",
    "manual": true
}
```

The _order_ is important, ie, you need to cancel the timer before you set it to manual.

**Comment by wokkeltje13** [comment]
tnx, this will solve my issue. 
when I want to trigger a new schedule, is sent the following payload
{
    "manual": false,
    "action": "on"
}
