### ISSUE TITLE
"Invalid properties: -lat -lon" but unclear where to set them

### ISSUE THREAD

**Issue by robcos** [mrgadget/node-red-contrib-eztimer#46]
I'm seeing this warning but I have no idea what to do about it
<img width="215" alt="Screenshot 2021-01-22 at 14 12 05" src="https://user-images.githubusercontent.com/64998/105501201-d52bf680-5cbb-11eb-89a5-f3e872c5d9b6.png">

**Comment by mrgadget** [comment]
Fair call - needs improvement, agree.  

It's the latitude/longitude on a default new node.   Just open the settings and set it (under `general info` - only displayed when required. ie, when a sun event is selected), or choose an on/off event that doesn't require lat/long.
