### ISSUE TITLE
Flows no longer triggering at the right time...

### ISSUE THREAD

**Issue by Swiftnesses** [mrgadget/node-red-contrib-eztimer#50]
Hello,

I've used EZTimer since the early days without issue - sometime recently my sunset / sunrise flows stopped working reliably (sunset / sunrise), they appear to trigger after they are due - example, today sunrise was 8am, they triggered at gone 9am (I'm not sure if this always happens, sometimes I don't see them trigger at all).

Has something changed recently that could have caused this?

Note, I use trigger only, the debug / node status shows the correct time, it just doesn't trigger at the correct time.

**Comment by mrgadget** [comment]
Hi, sorry for the delay in replying.  This is really strange - there haven't been any changes to core functionality for some time now, so strange it would stop all of a sudden.  I use it extensively in my flows (on/off, trigger, sun, tod etc) and it's fine for me.

If you turn on the `Emit all logs to debug` checkbox (bottom of config screen), and set it to run at a specific time, what events are emitted to the debug pane?

**Comment by mrgadget** [comment]
Hi @Swiftnesses, did you have any luck with this? Thanks.

**Comment by Swiftnesses** [comment]
I think it was a host clock issue, I think it's resolved. I'll close it.
