### ISSUE TITLE
How to configure the offset with the value of an entity

### ISSUE THREAD

**Issue by Yann0128** [mrgadget/node-red-contrib-eztimer#60]
Hi,
I check before to open this issue and I did not found precedent message on how to configure the offset with a value of an entity.
Conséquence will be : value of the entity can change from a card in HA and the offset is automatically updated.

Is it possible ? Can you explain how to do it ?

**Comment by mrgadget** [comment]
From docs, under [programmic control](https://github.com/mrgadget/node-red-contrib-eztimer?tab=readme-ov-file#programmatic-control), you're looking for `msg.payload.onoffset` or `msg.payload.offoffset`.  Ie, you'd need the payload to be a JSON object with a property of `onoffset`.

**Comment by Yann0128** [comment]
Thanks for the response ! I will check that.
Sorry, i did not understand the docs
