### ISSUE TITLE
Unsupported input

### ISSUE THREAD

**Issue by Yann0128** [mrgadget/node-red-contrib-eztimer#61]
Hi, 
I've got a problem in my flow. 
I'm using eztimer for triggers in my automatisation of shutters.
Many times, triggers work as I want too. But as many times, triggers don't work and say "unsupported input"
![image](https://github.com/user-attachments/assets/7b8ce856-0dac-4f56-9b86-00c896575acc)
Configuration of my nodes is very simple : 
![image](https://github.com/user-attachments/assets/d403f907-adc7-4e91-b317-029ecf919d2b)
And my payload is just the time of exécution :
![image](https://github.com/user-attachments/assets/f0944337-5d5b-4700-afd6-fc426736572d)

Can you tell me what I have to change in my configuration ?

**Comment by mrgadget** [comment]
Hi @Yann0128.  I can't quite figure out what you're trying to achieve with your input - are you trying to change the time of the trigger? Or are you just using eztimer as a runtime timer (ie, manual trigger)?

In it's most simple deployment, there is no input required into eztimer node - unless you're wanting to change properties at runtime, or trigger it.

I'd direct you to the [inputs](https://github.com/mrgadget/node-red-contrib-eztimer?tab=readme-ov-file#inputs) section of the readme - anything other than those strings as a simple payload will (well, should :)) result in the 'Unsupported Input' error.  Possibly you need to just send `trigger` if you're using your flow to trigger the timer?

**Comment by Yann0128** [comment]
Thanks for your response.
I don't want my input to change the time or other thing of the trigger, so the data of my input does no worry for me. But unfortunately it does worry for eztimer. And I dont understand what to put in to get eztimer satisfy.
As you prescrive, I've put "trigger" in the payload (with json nodes). 
I do not have the "unsupported input" message anyway, cool ! But I have an other problem : some of my entites are not commanded 1 time at the trigger, there ar commanded every 30 seconds. I dont understand why ? It was not the case before.

PS : sorry for my bad langage, English is difficult for me. 
![image](https://github.com/user-attachments/assets/ceeb07f6-cb83-4194-96f5-1f912d15087d)
![image](https://github.com/user-attachments/assets/18821e70-8205-4777-ba12-ea5ee9cb1e57)
![image](https://github.com/user-attachments/assets/1f4e7c2b-c8d0-4409-9520-f5973d400874)

**Comment by Yann0128** [comment]
Here is my flow.
Since I've change the payload for "trigger", actions are executing without respecting the conditions. It pass through the time plages and the trigger :\

[{"id":"489336a2183bf8fb","type":"api-current-state","z":"32b4f4becdef8afb","g":"bef5a84112edb585","name":"Jour férié ?","server":"58f04bff.fba834","version":3,"outputs":2,"halt_if":"off","halt_if_type":"str","halt_if_compare":"is","entity_id":"calendar.jours_feries_et_autres_fetes_en_france","state_type":"str","blockInputOverrides":false,"outputProperties":[{"property":"payload","propertyType":"msg","value":"1","valueType":"str"}],"for":"0","forType":"num","forUnits":"minutes","override_topic":false,"state_location":"payload","override_payload":"msg","entity_location":"data","override_data":"msg","x":770,"y":800,"wires":[["2a4c529b10353a8a","f5e378963c86922e"],["f1ca81e382f7cd35","d767bbc3385a2702"]]},{"id":"58f04bff.fba834","type":"server","name":"Home Assistant","addon":true,"rejectUnauthorizedCerts":true,"ha_boolean":"","connectionDelay":false,"cacheJson":false,"heartbeat":false,"heartbeatInterval":"","statusSeparator":"","enableGlobalContextStore":false}]

**Comment by mrgadget** [comment]
Ok so this is more a Node-Red usage issue than an issue with the node.  I still can't understand why you're using eztimer nodes - the result when you triggering it manually and  it is just outputting a payload of 1 - why not just change the payload to 1?

If you want to proceed with your current flow, you need to keep the payload until you've put it through the `time-range` nodes (as they need the time payload to make the correct decision), then use a `change` node to update the payload to `trigger` after the `time-range` nodes.

**Comment by mrgadget** [comment]
Also this:
```
msg = {"payload" : "trigger","payload.triggertime":"22: 30: 00"};
```
is technically valid, but won't do what you think it does, and the time is formatted wrong, and it does nothing as the time was already set to 22:30.  You can't write nested values in a string.   If you wanted to set `payload.triggertime` to `22:30:00`, you'd do this:

```
msg = { "payload": { "triggertime": "22:30:00" } }
```

Syntax is imporant.

Also you can't trigger it, as well as update the time in the same message.

Suggest you do some reading on javascript/JSON, and Node-RED.

**Comment by Yann0128** [comment]
I put change nodes just before every eztimer to send the time or value of the trigger on the payload and it works fine.
![image](https://github.com/user-attachments/assets/81262c6d-2405-4034-80a9-92ff71cf928a)
So shame it doesn't work without all those change nodes, by directly set the parameters on the node. But at least it works fine like that !
