### ISSUE TITLE
Programmatic changing the weekday doesn't work

### ISSUE THREAD

**Issue by stu-carter** [mrgadget/node-red-contrib-eztimer#8]
Hi again! 

I am trying to programmatically set the day on which a timer will be enabled (the user can choose via a drop-down).

I have used the string and property variants (e.g. 'wed false') to enable and disable days, but neither work for me.

Repro:

1. Enable all days in the node via the editor (default state)
2. Configure an on time for later today - the node status shows it will trigger today
3. Send a message disabling today such as 'wed false'
4. The status text doesn't change and the event will fire at the specified time today

I've included a flow to show this sending both 'wed false' in the payload and using 'payload.wed:false'.  

From the code, it looks like the weekdays array is not being updated - if I understand NodeRed, it is initially populated via the editor values, but thereafter, even if config.wed is updated, the weekday array remains constant which is what is used to update the schedule?

Thanks.

`[{"id":"d7569b3b.7891c","type":"debug","z":"459a5f7b.667b08","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","x":1070,"y":175,"wires":[]},{"id":"f252469a.a6f05","type":"inject","z":"459a5f7b.667b08","name":"emit config","topic":"","payload":"info","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":435,"y":225,"wires":[["f658e672.4f331"]]},{"id":"f658e672.4f331","type":"eztimer","z":"459a5f7b.667b08","name":"Disable day","autoname":"18:00 + 00:00:10","suspended":false,"sendEventsOnSuspend":false,"lat":"","lon":"","timerType":"1","startupMessage":false,"ontype":"2","ontimesun":"dawn","ontimetod":"18:00","onproperty":"payload","onvaluetype":"num","onvalue":1,"onoffset":0,"onrandomoffset":0,"offtype":"3","offtimesun":"dusk","offtimetod":"dusk","offduration":"00:00:10","offproperty":"payload","offvaluetype":"num","offvalue":0,"offoffset":0,"offrandomoffset":0,"mon":true,"tue":true,"wed":true,"thu":true,"fri":true,"sat":true,"sun":true,"x":770,"y":175,"wires":[["d7569b3b.7891c"]]},{"id":"1e08e22f.383f0e","type":"inject","z":"459a5f7b.667b08","name":"Disable for today (string)","topic":"","payload":"wed false","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":485,"y":175,"wires":[["f658e672.4f331"]]},{"id":"286c627d.fef786","type":"inject","z":"459a5f7b.667b08","name":"Disable for today (property)","topic":"","payload":"{\"wed\":false}","payloadType":"json","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":495,"y":125,"wires":[["f658e672.4f331"]]}]`

**Comment by mrgadget** [comment]
Hello again! I didn't realise how rubbish and full of bugs my node was until you started using it :)

Another bug located - always good to get rid of them, so thanks for that.  Are you able to test the github code again to make sure we're good prior to publish please?  It looks good to me with your test flow.  The next event time changes under the node and the output of `info` changes too.

Thanks,
Ben.

**Comment by fabnavigator** [comment]
I've been programming for 45 years, and I like to say "everything I've written before today is crap".

**Comment by mrgadget** [comment]
Yes - often thought similar things when looking back through code I've written previously - a good indication that constant education is occurring!

**Comment by stu-carter** [comment]
Hi - yep, checks out, smart way of fixing it!

Not rubbish code - I was pleasantly surprised to see you have unit tests, so I would blame the person who wrote those :) 

Thanks for the quick response.

**Comment by mrgadget** [comment]
Thanks - I like the ones that are easy to fix!  I had originally tried to keep it close enough to the upstream that I could merge changes but I think it's past that point now unfortunately - so bugs are mine and mine alone to fix.  Keep 'em coming! `1.0.11` published just now.

Cheers,
Ben.
